name: Storybook deployment

on:
    push:
        branches: [master]

env:
    CI: true

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js 10
              uses: actions/setup-node@v1
              with:
                  node-version: 10.x

            - run: npm install
            - run: npm run bootstrap
            - run: lerna run --scope examples build

            - name: Deploy storybook
              uses: JamesIves/github-pages-deploy-action@4.1.1
              with:
                  branch: gh-pages
                  folder: examples/storybook-static
                  target-folder: storybook

                  clean: true
                  # 👇 defines a list of files that should be kept during deployment
                  clean-exclude: |
                      CNAME
                      index.html
